source "https://rubygems.org"

gem "fastlane",   "~> 2.220"
gem "cocoapods",  "~> 1.14"

# Fastlane plugins
gem "fastlane-plugin-badge",         require: false
gem "fastlane-plugin-versioning",    require: false
